### ISSUE TITLE
Delete old text around CopperLaunch

### ISSUE THREAD

**Issue by admiraltiki** [superpowerlabs/copper-leaderboard#57]
Two bodies of text should be deleted as they are no longer relevant.

Delete following text:   
"Win exclusive "ORIGINAL SYNNER" NFTs by becoming top contributor during our launch auction. Ranking is based on net SYNR holding in your Ethereum wallet address. A snapshot at the end of the auction will decide the winners."

Delete following text:   
"How to participate Visit our launch auction, get $SYNR and hold them in your wallet"

**Comment by roquesrolando** [comment]
https://github.com/superpowerlabs/copper-leaderboard/pull/59
